version: "3.8"

services:
  docs:
    restart: always
    build:
      context: ../../
      dockerfile: environments/development/Dockerfile
    tty: true
    user: 1000:1000
    ports:
      - "8000:8000"
    volumes:
      - ../../../docs:/home/xccv/code